### ISSUE TITLE
Has denyhosts been removed from epel?

### ISSUE THREAD

**Issue by dpackman** [denyhosts/denyhosts#106]
My apologies if this is the wrong forum, but we just noticed that denyhosts is no longer in the epel repository. Is there a known reason for this?

**Comment by josev814** [comment]
Not sure when it was removed.  Last time I see it in Fedora is v28 according to RPMfind.  I've always installed it via git or pip.

**Comment by jccleaver** [comment]
It was "retired" in mid-2018, partially due to Fedora's (weird, IMHO) push to remove tcp_wrappers.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/X5DR3GSII2GRRKWKK5Q76KR4LXR2YFHD/

**Comment by josev814** [comment]
This was the last entry about denyhosts being retired.  on EPEL.
[https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/message/5UJ7RTEKZ3RASQM6METJBHFR5OGKD6O3/](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/message/5UJ7RTEKZ3RASQM6METJBHFR5OGKD6O3/)

**Comment by dpackman** [comment]
Thanks, guys. We use fail2ban but have found denyhosts a helpful auxiliary ... particularly when fail2ban ends up wedged.
