### ISSUE TITLE
All IP's trigger WARNING got invalid host (aaa.bbb.ccc.ddd), ignoring`

### ISSUE THREAD

**Issue by kkoenen** [denyhosts/denyhosts#110]
I get this line over and over in logs. Something to do with is_valid_ip_address from .util?

 `2019-12-22 06:25:05,188 - denyhosts   : WARNING  got invalid host (49.88.112.60), ignoring`

IP addresses are valid. Attached my .conf.

Thank you!

[denyhosts.conf.txt](https://github.com/denyhosts/denyhosts/files/3992525/denyhosts.conf.txt)

**Comment by josev814** [comment]
What version are you running?
/usr/bin/denyhosts.py --version

**Comment by josev814** [comment]
@kkoenen Can you pull down the latest version (master is at 3.1.2) and see if it resolves your issue?  I've added unit tests to check the is_valid_ip section with that ip that you included along with some other ips and the tests are all coming back correct.

**Comment by kkoenen** [comment]
Current version, I believe it's up to date;

```
kkoenen@vmi:/usr/share/denyhosts$ denyhosts.py --version
('DenyHosts version:', '3.1')
kkoenen@vmi:/usr/share/denyhosts$ python --version
Python 2.7.15+
kkoenen@vmi:/usr/share/denyhosts$
```

**Comment by kkoenen** [comment]
Downloaded source, installed python-ipaddr, runs fine now. Thanks.
