### ISSUE TITLE
Denyhosts Sync Server

### ISSUE THREAD

**Issue by josev814** [denyhosts/denyhosts#121]
Is it possible to have denyhosts_sync that @janpascal owns, moved over as a new repository under the DenyHosts organization?  That way the sync server can be supported under the DenyHosts Organization, and users can then easily find the Sync server.  I think it would allow users to spin up additional sync servers, and give us the ability to further develop it under the DenyHosts "branding".

I don't have permission to fork or create a repo under the DenyHosts organization, that's why I was adding @mruffalo to the assignees.

**Comment by mruffalo** [comment]
@josev814 You're an owner of this GitHub organization now.

**Comment by josev814** [comment]
Thank you
