### ISSUE TITLE
Denyhosts and OpenVPN service

### ISSUE THREAD

**Issue by AdasOsorus** [denyhosts/denyhosts#122]
My server has some "attack" on open-vpn services.

@josev814 , do you know if denyhosts service can be adapted in such way to add these IP to host.deny?

Reference...
`cat /var/log/syslog | grep "ovpn-server"`
```
Apr 30 16:31:29 HOMESERVER ovpn-server2[1187]: TCP connection established with [AF_INET]128.14.134.134:50298
Apr 30 16:31:29 HOMESERVER ovpn-server2[1187]: 128.14.134.134:50298 WARNING: Bad encapsulated packet length from peer (5635), which must be > 0 and <= 1627 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
Apr 30 16:31:29 HOMESERVER ovpn-server2[1187]: 128.14.134.134:50298 Connection reset, restarting [0]
Apr 30 16:31:29 HOMESERVER ovpn-server2[1187]: 128.14.134.134:50298 SIGUSR1[soft,connection-reset] received, client-instance restarting
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: TCP connection established with [AF_INET]107.175.93.50:63799
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:63799 WARNING: Bad encapsulated packet length from peer (5635), which must be > 0 and <= 1627 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:63799 Connection reset, restarting [0]
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:63799 SIGUSR1[soft,connection-reset] received, client-instance restarting
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: TCP connection established with [AF_INET]107.175.93.50:51590
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:51590 WARNING: Bad encapsulated packet length from peer (5635), which must be > 0 and <= 1627 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:51590 Connection reset, restarting [0]
Apr 30 16:34:48 HOMESERVER ovpn-server2[1187]: 107.175.93.50:51590 SIGUSR1[soft,connection-reset] received, client-instance restarting
(...)
```
```

**Comment by josev814** [comment]
Using the userdefined regex you could have it use this regex ```ovpn-server[0-9]+\[[0-9]+\]:\s(?P<host>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):[0-9]+\sWARNING:\s.*possible active attack``` Since only a host is really required, that regex would capture the host.  The only issue I see is that in your logs they're hitting once.  Hopefully, there are multiple attack attempts, so you can have it set to at least 3 before blocking the ip address.

[Can I supply additional regular expressions to DenyHosts](https://github.com/denyhosts/denyhosts/wiki/Can-I-supply-additional-regular-expressions-to-DenyHosts)

**Comment by AdasOsorus** [comment]
@josev814 , so if I understand correctly, I just have to add this regex into the conf file under 
USERDEF_FAILED_ENTRY_REGEX=    
Ex.:
`USERDEF_FAILED_ENTRY_REGEX= ovpn-server[0-9]+\[[0-9]+\]:\s(?P<host>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):[0-9]+\sWARNING:\s.*possible active attack`

Is that correct?

**Comment by josev814** [comment]
Yes, but you should remove that empty space after REGEX= in order to ensure that the beginning whitespace doesn't mess it up.

**Comment by josev814** [comment]
within prefs.py
```                    name = m.group('name').upper()
                    value = self.environ_sub(m.group('value'))
...............
                    if name == 'USERDEF_FAILED_ENTRY_REGEX':
                        self.__data['USERDEF_FAILED_ENTRY_REGEX'].append(re.compile(value))```

That code will read the config file.  Then is the name matches the userdef regex, it will take the userdef regex you make and to a regex compile and append it to the internal userdef regexes to use to test lines against.

I just wanted to put the code here, so you can see how it works.

**Comment by AdasOsorus** [comment]
Ok... super!
I will give it a try now ;)

**Comment by josev814** [comment]
Yes it will
I use [regex101.com](http://regex101.com) to test regex patterns.  It's really helpful to build regex.  Just make sure the select the python version for regex.

**Comment by AdasOsorus** [comment]
@josev814  any meen we can have a qui "chat"... ?

**Comment by AdasOsorus** [comment]
@josev814 It seems that the command isn't pass to iptables (USERDEF_FAILED_ENTRY_REGEX) ... how I can give you debugging info? or any means to help troubleshoot?

**Comment by josev814** [comment]
I can take the lines from the log you posted about and write a quick unittest to see why it's not getting written into the iptables.

**Comment by AdasOsorus** [comment]
@josev814 , yo can close the issue... I added a cron task every minute with this : 
`cat /var/log/syslog | grep "ovpn-server" | grep -v "TRONIC CRON" | grep "Bad encapsulated packet" | awk '{print $6}' | awk -F ":" '{print $1}' | uniq | xargs addenemy >> /var/log/openVPNAttack.log`

where **addenemy** is :
```
#!/bin/sh
#
#Source: https://www.lammertbies.nl/comm/info/iptables
#
strIPTablesPath=/usr/sbin
strCurrentDateTime=`date +"%Y-%m-%d %T"`
#
# Use to remove a rule
# iptables -D INPUT -s $strIPvar -j DROP
#

for strIPvar in "$@"
do
  $strIPTablesPath/iptables -L -n -v | grep -q $strIPvar
  RETVAL=$?
  if [ $RETVAL -eq 0 ]; then
    echo "IP address already in blocklist: $strIPvar"
    #exit 0
  else
    echo "Adding enemy $strIPvar - $strCurrentDateTime"
    $strIPTablesPath/iptables -I INPUT -s $strIPvar -j DROP
  fi
done
#
```

So I remove the check from **denyhost.conf** from **USERDEF_FAILED_ENTRY_REGEX=**

Thank you again for your help.
Martin.
