### ISSUE TITLE
Denyhosts stops after installing iptables rule in Debug mode

### ISSUE THREAD

**Issue by gswan** [denyhosts/denyhosts#136]
Denyhosts is operating (Python-3.7.4) in daemon mode (Linux).
A new ssh attack is detected and the attempt to install an iptables rule succeeds.
Immediately following the iptables rule creation, denyhosts terminates.

Debug log:
2020-05-08 20:11:41,250 - denyhosts   : DEBUG    /var/log/sshd.log has additional data
2020-05-08 20:11:41,262 - denyhosts   : DEBUG    user: hadoop - host: 5.101.151.82 - success: 0 - invalid: 1
2020-05-08 20:11:41,272 - denyhosts   : DEBUG    new hosts: ['5.101.151.82']
2020-05-08 20:11:41,272 - denyhosts   : DEBUG    Trying to create iptables rules
2020-05-08 20:11:41,272 - denyhosts   : DEBUG    Running iptabes rule: /sbin/iptables -I INPUT -s 5.101.151.82 -j DROP
2020-05-08 20:11:41,272 - denyhosts   : INFO     Creating new firewall rule /sbin/iptables -I INPUT -s 5.101.151.82 -j DROP

After the rule was successfully created, denyhosts was no longer running and had to be restarted.

**Comment by gswan** [comment]
The denyhosts startup command:
/usr/bin/env python3 /usr/bin/denyhosts.py --daemon --config=/etc/denyhosts/denyhosts.conf

**Comment by gswan** [comment]
VERSION = "3.0" from version.py

**Comment by josev814** [comment]
@gswan Is this occurring every time you are running denyhosts?

You can also get the denyhosts version by running:
```python3 /usr/bin/denyhosts.py --version```

I'm currently running Version 3.1.2 of DenyHosts, so I'll have to grab an older version of DenyHosts to test out your issue.

Where did you get your version of DenyHosts from?
Also what OS/Version are you running on?

**Comment by gswan** [comment]
@josev814 Yes. On several new hosts that are using Python3 only. Previously I used Python2 for denyhosts.
```
# python3 /usr/bin/denyhosts.py --version
DenyHosts version: 3.0
```
I downloaded the denyhosts source from github.com:
https://github.com/denyhosts/denyhosts/archive/v3.1.tar.gz

The OS is Linux (5.4.2) on x86_64.

**Comment by josev814** [comment]
Can you use this tgz for installing?
https://github.com/denyhosts/denyhosts/releases/download/v3.1/DenyHosts-3.1.2.tar.gz

When you run python --version does it display python or python3?
If it displays python3, you'll have to run the python3 conversion script.

From what I've noticed with the conversion script doesn't always pull the correct python3 location.  
You can test running the py3loc code within your terminal to check if it will return the correct path to python3 for you, or you can change the ```$()``` code to just be the path to your python3.  ```whereis python3 | awk '{ print $2 }'``` I've been changing it over to using ```$(which python3)``` which allows it to work for Debian.

Debian 9:
Command: whereis python3 | awk '{ print $2 }'
Result: /usr/bin/python3.5-config
Command: which python3
Result: /usr/bin/python3

**Comment by gswan** [comment]
I grabbed that tgz and installed it.
Only python3 on this machine, at /usr/bin/python3.
Running OK so far. I'll wait for a few attacks and see how it goes.
Thanks for the update.

**Comment by gswan** [comment]
It scanned the sshd log and added two new iptables rules and then stopped.
Both of these report correct paths.
```
# whereis python3 | awk '{ print $2 }'
/usr/bin/python3.7
# which python3
/usr/bin/python3
```
There doesn't seem to be any detail in the log to identify where it is stopping.
However it does successfully set the iptables rule before stopping.

**Comment by gswan** [comment]
It appears that it was killed by sending the debug signal to it (SIGUSR1).
Maybe this is a clue.

```
# /etc/rc.d/init.d/denyhosts start
starting DenyHosts:  /usr/bin/python3 /usr/bin/denyhosts.py --daemon --config=/etc/denyhosts/denyhosts.conf
# ps -He | grep python
18231 ?        00:00:00   python3
# /etc/rc.d/init.d/denyhosts debug
sent DenyHosts SIGUSR1
# ps -He | grep python
#
```
I'll run it without debug mode and see if I find anything else.

**Comment by gswan** [comment]
After running the updated version on a couple of hosts for the day it appears to be running OK and not stopping after adding an iptables rule. 
The only thing I saw is that sending it a debug signal appeared to kill it, however debug mode is not used in normal operation.

**Comment by josev814** [comment]
I'll have to look into the debug mode.  I never use that option.  So, there must be something in that mode that's causing an error to trigger that isn't being caught properly and causing the exit

**Comment by josev814** [comment]
@gswan Could I get a copy of the config file you have?

I tested denyhosts on Debian Buster in Debug mode and it was working fine for me.  I'm wondering if there's a setting that you have set that I don't that's causing debug mode not to work.

**Comment by gswan** [comment]
Here are the uncommented items in the config file I have. Email address have been changed.

SECURE_LOG = /var/log/sshd.log
HOSTS_DENY = /etc/hosts.deny
PURGE_DENY =
BLOCK_SERVICE  = sshd
DENY_THRESHOLD_INVALID = 2
DENY_THRESHOLD_VALID = 3
DENY_THRESHOLD_ROOT = 3
DENY_THRESHOLD_RESTRICTED = 1
DETECT_DOVECOT_LOGIN_ATTEMPTS = NO
WORK_DIR = /etc/denyhosts/data
ETC_DIR = /etc
SUSPICIOUS_LOGIN_REPORT_ALLOWED_HOSTS=YES
HOSTNAME_LOOKUP=YES
LOCK_FILE = /run/denyhosts.pid
IPTABLES = /sbin/iptables
ADMIN_EMAIL = admin@example.com
SMTP_HOST = localhost
SMTP_PORT = 25
SMTP_FROM = DenyHosts <root@servername>
SMTP_SUBJECT = DenyHosts Report from servername
ALLOWED_HOSTS_HOSTNAME_LOOKUP=NO
AGE_RESET_VALID=5d
AGE_RESET_ROOT=25d
AGE_RESET_RESTRICTED=25d
AGE_RESET_INVALID=10d
RESET_ON_SUCCESS = yes
DAEMON_LOG = /var/log/denyhosts
DAEMON_SLEEP = 30s
DAEMON_PURGE = 1h
SYNC_UPLOAD = no
SYNC_DOWNLOAD = no

**Comment by josev814** [comment]
I found where the bug was for the daemon being killed when debug was passed.  I have a fix for it, and I'm just waiting for the travis-ci builds to pass

**Comment by josev814** [comment]
Can you validate that the latest update resolved the issue for you?

**Comment by gswan** [comment]
I get this when starting now:
```
starting DenyHosts:  /usr/bin/env python3 /usr/bin/denyhosts.py --daemon --config=/etc/denyhosts/denyhosts.conf
Traceback (most recent call last):
  File "/usr/bin/denyhosts.py", line 18, in <module>
    from DenyHosts.deny_hosts import DenyHosts
  File "/usr/lib/python3.7/site-packages/DenyHosts/deny_hosts.py", line 24, in <module>
    from .sync import Sync
  File "/usr/lib/python3.7/site-packages/DenyHosts/sync.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by josev814** [comment]
You'll need to install the requests module for python3.7.  I'm a bit surprised it's not already installed.
If you have pip installed you can do ```pip3 install requests``` or ```pip install requests```

If you're not using pip it should be available as a distribution package as python3-requests.

We're looking at resolving Bug #149 and the cleaner way of handling the sync issues occurring and overloading the sync server is to use the Requests library to handle it.

**Comment by gswan** [comment]
Looks like that fixed it. 
So far so good. Sending a SIGUSR1 to go into debug mode worked OK.
Thanks.
