### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by josev814** [denyhosts/denyhosts#138]
Anyone interested in helping to sponsor the development work and covering costs of the VM sync server can sign up at https://github.com/sponsors.

**Comment by josev814** [comment]
@adriel Could you look into signing up for that?  That way users will be able to sponsor you to help cover costs of the sync server.

**Comment by adriel** [comment]
Worth a try. Just signed up and now in the waiting list.

**Comment by adriel** [comment]
Hey @josev814 how'd you get `denyhosts/denyhosts` to be a "Featured work" on your [sponsor](https://github.com/sponsors/josev814) page?

I can only select my own repos from the dropdown list in the [sponsor settings] page.(https://github.com/sponsors/adriel/dashboard/profile).

**Comment by ZerooCool** [comment]
Just signed up and now in the waiting list.

**Comment by josev814** [comment]
@adriel It might be because I'm an owner of the Denyhosts org now.  I have the all of the Denyhosts repos available under the featured work page.

I added you to the list of sponsors when people click on the sponsor button.

**Comment by ZerooCool** [comment]
I'm discovering this sponsor system.
At the moment he is waiting for me.

If I understand correctly, it is each developer who gives the possibility of being sponsored, but, it is not the project itself?

**Comment by josev814** [comment]
That's correct.  So, if you want to sponsor a specific developer on a project they should be in the .github/funding.yml file.  Then on the repo it will show a sponsors button at the top.  From there, you can click on Sponsor, and it will give you the option of sponsoring a specific developer.

**Comment by ZerooCool** [comment]
Yes, I can see this button now, I had not yet spotted it. Very interesting, on the form, on the substance I do not know. Have you ever been able to use this kind of practice on other projects, and is there really any kind support?

I have often heard of its people, who fill the pots, but, in truth, I have never been part of it, and, it seems to me that there is a dark side, when some seem to fill very large pots, the one or others who are seriously involved, do not fill any pot.

In this context, I think I understand that it is above all about encouraging a developer who would be working on a certain theme, to push him to move forward, as for example, I saw that Adriel works on Docker, and, is therefore able to master this aspect, better than another who would not work with Docker.

Are there any special conditions to become a developer who can be supported on the project?
If a person wishes to participate, to what extent can they claim to become a sponsorable member to participate in the project?

**Comment by ZerooCool** [comment]
I would have a supplementary question, following the validation of my account, to add the sponsors button on my projects.

I see on your profile @josev814  that you have advanced 12% of your goal, however, I do not see the list of your sponsors.

I was wondering if this was normal, because generally sponsors like to be displayed, that's why they sponsor, right?

I simply may not have found them, or, perhaps, I have not yet fully understood everything.

**Comment by josev814** [comment]
@ZerooCool I don’t have any sponsors at the moment.  I did sponsor Adriel and he’s at 12%.  So, maybe that’s what you’re seeing.  When looking at my profile it shows that I’m sponsoring him.  When looking at his profile I show up as a sponsor.

**Comment by ZerooCool** [comment]
Ok, I think I understood correctly by now, if we have several sponsors, we don't know who gave how much, so there is no difference displayed between small and large sponsors.
