### ISSUE TITLE
ImportError: No module named ipaddr

### ISSUE THREAD

**Issue by jeg139** [denyhosts/denyhosts#143]
Hi,

I tried to install denyhosts on debian 10 and when i launch the install script from github repo this is what i get ( i added a print into util.py to see what py_version return ) :

sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from DenyHosts.util import normalize_whitespace
  File "/tmp/denyhosts/DenyHosts/util.py", line 13, in <module>
    from ipaddr import IPAddress
ImportError: No module named ipaddr

i tried to import the module from another script and it run with no error, i tried to put the import line at the beginning of the script util.py, same error.

if i use python -m ipaddr i have no error.

i also tried in /tmp folder and /home folder same results.

thanks.

**Comment by ZerooCool** [comment]
I have the same alert with Debian 10 Buster, for ipaddr, and i can install with :
```
sudo apt-get install python-pip
sudo pip install ipaddr
```
Then, install other modules required from the requirements.txt with the same command : 
`sudo pip install `

But then, i can launch denyhosts.
For me, the steep 
"Starting DenyHosts Manually" from the readme fil doesn't work

```
sudo daemon-control start
sudo: daemon-control : commande introuvable
```

```
sudo python /usr/local/bin/denyhosts --config /etc/denyhosts.conf --daemon
python: can't open file '/usr/local/bin/denyhosts': [Errno 2] No such file or directory
```

**Comment by ZerooCool** [comment]
If i test for launch denyhost with a service : 

```
sudo service denyhosts restart
Failed to restart denyhosts.service: Unit denyhosts.service is masked.
/etc$ cd /etc/init.d
/etc/init.d$ sudo ln -s /usr/share/denyhosts/daemon-control denyhosts
ln: impossible de créer le lien symbolique 'denyhosts': Le fichier existe
```

**Comment by ZerooCool** [comment]
@jeg139 

Installation de la branche Master de Denyhosts : 

Prérequis !
Créer un utilisateur debian qui sera sudoers pour tester l'installation :
```
adduser debian
apt-get install sudo
usermod -a -G sudo debian
```

Installer les paquets suivants :
`sudo apt-get install git`

Installer les paquets et modules python suivants :
```
sudo apt-get install python
sudo apt-get install python-pip
sudo pip install ipaddr
sudo pip install mock
sudo pip install requests
sudo pip install configparser
```

Installer Denyhosts :
```
sudo git clone https://github.com/denyhosts/denyhosts
cd denyhosts
sudo python setup.py install
sudo cp denyhosts.conf /etc
sudo cp daemon-control-dist daemon-control
```

Attention aux doubles quottes quand on copie les 3 lignes de configuration !
`sudo nano daemon-control`

Commenter et remplacer les 3 lignes suivants :
```
###############################################
#### Edit these to suit your configuration ####
###############################################
#DENYHOSTS_BIN = "/usr/sbin/denyhosts.py"
#DENYHOSTS_LOCK = "/run/denyhosts.pid"
#DENYHOSTS_CFG = "/etc/denyhosts.conf"

DENYHOSTS_BIN = "/usr/bin/denyhosts.py"
DENYHOSTS_LOCK = "/var/lock/subsys/denyhosts"
DENYHOSTS_CFG = "/etc/denyhosts.conf"
```

```
cd /etc/init.d
sudo ln -s /usr/share/denyhosts/daemon-control denyhosts
cd ~
sudo mv denyhosts /usr/share/
cd /usr/share/denyhosts/
sudo cp denyhosts.py /usr/bin/
```

Créer le fichier auth.log qui n'est pas présent par défaut :
`sudo touch /var/log/auth.log`

```
sudo systemctl enable denyhosts
denyhosts.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable denyhosts
update-rc.d: error: denyhosts Default-Start contains no runlevels, aborting.
```

```
sudo systemctl status denyhosts
sudo systemctl restart denyhosts
sudo systemctl status denyhosts
htop
```

Copier la configuration proposée par après, pour renforcer les règles de Denyhosts.
Redémarrer Denyhosts pour prendre en compte les changements.

Si je htop puis kill le pid du daemon de denyhosts, alors, le status est en exit et Denyhosts ne fonctionne plus.
`sudo service denyhosts status`
Par contre, la commande start ne semble alors pas démarrer Denyhosts !
`sudo service denyhosts start`
Denyhosts va bien redémarrer avec restart :
`sudo service denyhosts restart`

**Reste encore à tester cette configuration, pour voir si elle bloque réellement les IP !!??**

From : https://mediawiki.visionduweb.fr/index.php?title=Sommaire_Sécurité#Installer_DenyHosts_depuis_le_d.C3.A9p.C3.B4t_officiel_sur_Github

**Comment by jeg139** [comment]
Hi thanks for the reply,

what i do to get it work for me :

1 - remove all denyhosts folder in /tmp and /home

2 - install ipaddr in root

3 - download denyhosts in /tmp folder and then install it with no more error
