### ISSUE TITLE
ValueError: '68.ip-51-38-131.eu' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by bigwavedave42** [denyhosts/denyhosts#145]
Just installed Git version of denyhosts (had previously been running 2.6 via RPM) and am getting the following:

daemon-control start
starting DenyHosts:  /usr/bin/env python /usr/bin/denyhosts.py --daemon --config=/etc/denyhosts.conf
Traceback (most recent call last):
  File "/usr/bin/denyhosts.py", line 232, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/lib/python2.7/site-packages/DenyHosts/deny_hosts.py", line 85, in __init__
    offset = self.process_log(logfile, last_offset)
  File "/usr/lib/python2.7/site-packages/DenyHosts/deny_hosts.py", line 481, in process_log
    if not is_valid_ip_address(host):
  File "/usr/lib/python2.7/site-packages/DenyHosts/util.py", line 197, in is_valid_ip_address
    ip = IPAddress(process_ip)
  File "/usr/lib/python2.7/site-packages/ipaddr.py", line 77, in IPAddress
    address)
ValueError: '68.ip-51-38-131.eu' does not appear to be an IPv4 or IPv6 address

DenyHosts exited abnormally`

Centos 7
Python 2.7.5

I cleared out /var/lib/denyhosts as I saw a previous issue reported related to offset.  It seems that the closest thing I can find in my related logs would be in /var/log/secure that reference the host mentioned:

grep 68.ip-51-38-131.eu /var/log/secure
May 17 05:25:46 helga sshd[11226]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=68.ip-51-38-131.eu  user=root
May 17 05:30:24 helga sshd[11685]: User nagios from 68.ip-51-38-131.eu not allowed because none of user's groups are listed in AllowGroups
May 17 05:30:24 helga sshd[11685]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=68.ip-51-38-131.eu  user=nagios
May 17 05:33:01 helga sshd[11952]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=68.ip-51-38-131.eu  user=root
May 17 05:35:17 helga sshd[12207]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=68.ip-51-38-131.eu

So grabbing one of those instances:
grep "May 17 05:30" /var/log/secure
May 17 05:30:24 helga sshd[11685]: User nagios from 68.ip-51-38-131.eu not allowed because none of user's groups are listed in AllowGroups
May 17 05:30:24 helga sshd[11685]: input_userauth_request: invalid user nagios [preauth]
May 17 05:30:24 helga sshd[11685]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=68.ip-51-38-131.eu  user=nagios
May 17 05:30:24 helga sshd[11685]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "nagios"
May 17 05:30:26 helga sshd[11685]: Failed password for invalid user nagios from 51.38.131.68 port 48818 ssh2
May 17 05:30:27 helga sshd[11685]: Received disconnect from 51.38.131.68 port 48818:11: Bye Bye [preauth]
May 17 05:30:27 helga sshd[11685]: Disconnected from 51.38.131.68 port 48818 [preauth]

Could it be choking on an entry in a different log?  Is there a way for DenyHosts to handle this in /var/log/secure better?

**Comment by josev814** [comment]
What I'm seeing is that the regex below in regex.py is picking up that host from this line.  
```
May 17 05:30:24 helga sshd[11685]: User nagios from 68.ip-51-38-131.eu not allowed because none of user's groups are listed in AllowGroups
```

```
FAILED_ENTRY_REGEX5 = re.compile(r"""User (?P<user>.*) .*from (?P<host>.*) not allowed because none of user's groups are listed in AllowGroups$""")
```
In deny_hosts:476 it's setting host to the parse host from that line, the 481 is checking to see if it's a valid ip address.  That's in util.py:193.  

Whey trying to run 68.ip-51-38-131.eu through `ipaddress.ip_address()`. That's when I see the error.  It seems that we're expecting an ip address and not a hostname.

I did test with `socket.gethostbyname('68.ip-51-38-131.eu')` and that will return the ip address.  It will require hostname lookups to be active.  I can put a patch in, to do hostname lookups if it's enabled in the config file.  Right now hostname lookups are only active on allowedhosts.  I don't see a reason why we shouldn't have it where if hostname lookups are active in the config file that we check the hostname before checking if it's a valid ip address.

**Comment by josev814** [comment]
@bigwavedave42 I have the fix for that merged into the master branch.  Can you validate that it resolves your issue?  Also, make sure that in your denyhosts.conf file you have HOSTNAME_LOOKUP around line 205 set to YES.

**Comment by bigwavedave42** [comment]
I did a master update, and am now at 75cc6ec
I already had HOSTNAME_LOOKUP set to YES in denyhosts.conf

That seems to have done the trick!  It seems to start the daemon correctly now.  I think this can be closed, but I'll leave that honor to you... in case you have some follow-up.
