### ISSUE TITLE
denyhosts missing lsb tags

### ISSUE THREAD

**Issue by jeg139** [denyhosts/denyhosts#146]
Hi, 

denyhosts working fine but i have this warning,

insserv: warning: script 'denyhosts' missing LSB tags
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `denyhosts'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `denyhosts'

maybe someone have an idea to avoid this warning

**Comment by josev814** [comment]
This looks to be something in regards to the denyhosts service init.d script.
[https://wiki.debian.org/LSBInitScripts](https://wiki.debian.org/LSBInitScripts)
I'm not sure how the init.d script is being made.  I'll have to look into how distutils handles creating service init.d scripts.

**Comment by jeg139** [comment]
Yes the init.d script is symlinked with deamon-control, written in python, i don't know how to add the lsb init in python. In a /bin/sh script the init part can be easier to implement.

**Comment by josev814** [comment]
Do you see the denyhosts.service file anywhere.  In our repo we have the denyhosts.service file, and if you simply copy that into /etc/systemd/system and then run systemctl enable denyhosts.service, the systemd and service commands should work as expected.  I just tested it out myself.

Did you install using a deb, rpm or from this repo?

**Comment by jeg139** [comment]
I installed it from the github repo. But i run it as a deamon not a service.
If running it as a service avoid the warning, i can use it like this. I'll try later and tell you. Thank you.

**Comment by jeg139** [comment]
I do a fresh install from the repo and add denyhosts.service into /etc/systemd/system and then run systemctl enable denyhosts.service.
Like you said it work perfectly, no warning and the service is up when i reboot.

Thanks again this is the right way for debian.

**Comment by josev814** [comment]
@ZerooCool as jeg139 mentioned here you may need to add to your documentation for Debian is run ```systemctl enable denyhosts.service``` after copying over the denyhosts.service file

**Comment by ZerooCool** [comment]
Yes, just.
The next test, ASAP.

**Comment by ZerooCool** [comment]
enable KO
start OK

https://www.youtube.com/watch?v=0n8mC0sTtsA

**Comment by josev814** [comment]
@ZerooCool jeg139 was stating that the service would automatically run on a reboot.  Not that it was necessary to do a reboot.  I'm closing this issue since this is resolved.  I do have another ticket open specifically for Debian and installing the service file when using dpkg. #170

**Comment by ZerooCool** [comment]
Ok for me, that doesn't seem to be resolved, because, I imagine that the enable command should be able to be executed without having to restart the server.
I may not understand.
We will see later, during the next installations of the master.
