### ISSUE TITLE
DenyHosts from Github with or without --purge

### ISSUE THREAD

**Issue by ZerooCool** [denyhosts/denyhosts#153]
On my production server with the version of DenyHosts 2.10-2:
```
htop
starting DenyHosts:  /usr/bin/env python /usr/sbin/denyhosts.py --daemon --purge --config=/etc/denyhosts.conf
```

On my LWS test server with the DenyHosts 3.1.2-2 version of the master branch of Github, I do not have the --purge command:
```
htop
starting DenyHosts:  /usr/bin/env python /usr/sbin/denyhosts.py --daemon --config=/etc/denyhosts.conf
```

I read that --purge does not work in daemon mode :

> When run in --daemon mode the following flags are ignored:
> --file, --purge, --migrate, --sync, --verbose

How then to take into account the configuration which allows purging, does it still work ?
According to the manpage, the --sync option cannot also be passed, however, the server synchronizes correctly.
I do not understand the current operation which allows synchronization without seeing the option appear. (--sync)
Because of this, will the purge still be carried out?

Should DenyHosts be launched otherwise?

> Usage: /usr/sbin/denyhosts [-f logfile | --file=logfile] [ -c configfile | --config=configfile] [-i | --ignore] [-n | --noemail] [--purge] [--migrate] [--daemon] [--sync] [--version]

**Comment by josev814** [comment]
Sync only works in the foreground.  It allows you to do a manual sync, but only when dh isn't running.  Otherwise the sync will sync up new entries in from your server up to the sync server and down from it.  As for the purging, I'm not sure.  I'd have to review the code to see how that portion is handled.  I know that until today the --purgeip wasn't working.  I just merged that in today, since it's a bug that I ran into when doing tests for another bug.

To do a sync you would do /usr/sbin/denyhosts.py --sync --config=/etc/denyhosts.conf
For the --purge I would assume it's the same, but replace sync with purge.

**Comment by josev814** [comment]
As dh runs it will purge ips determined on your sync interval set in denyhosts.conf and will remove entries defined in your time of PURGE_DENY.

To run purge manually:

```/usr/sbin/denyhosts.py --purge --config=/etc/denyhosts.conf```
Reviewing the code does this
denyhosts.py:
  sets variable in denyhosts to 1
  checks to ensure that purge is set and that daemon and foreground aren't set.
  gets PURGE_DENY setting from .conf file
  calls Purge Class from denyfileutil.py passing prefs and PURGE_DENY setting
denyfileutil.py
  backs up hosts.deny file
  reads the data from the backupfile
  creates temp file
  checks timestamp of each entry, and adds it to the remove list if the time is < than the current time
  the list of purged ips are then passed to AbusiveHosts.purge_hosts to remove them from the system.
  After that for any plugins in PLUGIN_PURGE that are defined, the purged_ips are then passed to the plugins.

I hope that answers your question of how purge works.  If you want to purge all then use the --purge-all flag.

**Comment by ZerooCool** [comment]
The same error in #155 

```
/usr/sbin/denyhosts.py --sync --config=/etc/denyhosts.conf
Error synchronizing data
'Sync' object has no attribute 'get_denied_hosts'
```
