### ISSUE TITLE
Incorrect comparison causes all successful logins be labeled suspicious [patch]

### ISSUE THREAD

**Issue by mpuzio** [denyhosts/denyhosts#16]
There appears to be a long-standing bug in loginattempt.py, which has recently become much more visible due to a change in Python implementation. The problem is in line 74, where the expression "self.__abusive_hosts_invalid.get(host, 0) > self.__deny_threshold_invalid" is part of the condition used for the decision whether a particular login attempt is to be considered suspicious. While the intention of that comparison is clear, python does not execute it as intended. The types of expressions on both sides of the comparison differ, they are 'instance' (of class CounterRecord) and 'int'. Python orders values of different types by type name, and as a result the above expression always evaluates as either true or false, regardless of values on both sides of the comparison. As it happens, python 2.7.3 considers 'instance' < 'int', while in python 2.7.5 we have 'instance' > 'int'. Thus, in denyhost(s) running with an older version of python, condition was always false, and suspicious login related code was effectively dead. On the other hand, with newer python the condition is always true, and all successful logins are branded as suspicious, which is easy to spot in the logs.

This issue affects other users, and in fact was reported on the original denyhosts bug tracker: https://sourceforge.net/p/denyhosts/bugs/61/
That report contains more details, as well as a patch that is very similar to one included below.

This issue concerns denyhost 2.9, but the problem is likely still present in the master branch on GitHub, as of this writing.

The solution is to modify the condition to compare two integers:

```python
--- loginattempt.py.orig        2014-06-01 19:42:11.000000000 -0500
+++ loginattempt.py     2015-01-08 18:37:42.405868216 -0600
@@ -76,7 +76,7 @@
             self.__abusive_hosts_invalid[host].reset_count()
 
 
-        if success and self.__abusive_hosts_invalid.get(host, 0) > self.__deny_threshold_invalid:
+        if success and self.__abusive_hosts_invalid.get(host).get_count() > self.__deny_threshold_invalid:
             num_failures = self.__valid_users_and_hosts.get(user_host_key, 0)
             self.__suspicious_logins[user_host_key] += 1
             if self.__suspicious_always or host not in self.__allowed_hosts:
```

**Comment by slicer69** [comment]
Thank you, I will commit this patch.

**Comment by mpuzio** [comment]
Thanks a lot. Here is a slightly cleaner version that uses [] rather than get(). This is to ensure that Counter's `__getitem__` is called if CounterRecord for host does not yet exist. In practice this does not matter much, as the CounterRecord object is autovivified by an earlier code. But since [] is used everywhere else in the code, there is no point using get() just once.

```pyhon
--- loginattempt.py.orig        2014-06-01 19:42:11.000000000 -0500
+++ loginattempt.py     2015-01-09 15:02:14.751460857 -0600
@@ -76,7 +76,7 @@
             self.__abusive_hosts_invalid[host].reset_count()
 
 
-        if success and self.__abusive_hosts_invalid.get(host, 0) > self.__deny_threshold_invalid:
+        if success and self.__abusive_hosts_invalid[host].get_count() > self.__deny_threshold_invalid:
             num_failures = self.__valid_users_and_hosts.get(user_host_key, 0)
             self.__suspicious_logins[user_host_key] += 1
             if self.__suspicious_always or host not in self.__allowed_hosts:
```

**Comment by slicer69** [comment]
Thank you, I commited this.
