### ISSUE TITLE
Iptables would be a prerequisite for Denyhosts ?

### ISSUE THREAD

**Issue by ZerooCool** [denyhosts/denyhosts#163]
By default, it seems to me that DenyHosts now uses iptables, it seems to me that this is enabled in the configuration, therefore, iptables would be a prerequisite. You confirm ?

**Comment by josev814** [comment]
iptables is enabled by default, but I wouldn't say it's a prerequisite.  It can be disabled by commenting out iptables in the config file, so it should be viewed as optional.  It's just part of the setup process that someone should do when initially configuring denyhosts.

**Comment by josev814** [comment]
@ZerooCool I saw that in your recent documentation update, that you marked as iptables as not a dependency.  Can you mark this bug as resolved then?

**Comment by ZerooCool** [comment]
For the moment, I think that it should be left open, and, test again, if everything works correctly, for an installation without iptables.
Does denyhosts behave correctly?
Blocking traffic?
Doesn't generate log messages, due to the absence of Iptables?

**Comment by josev814** [comment]
Not having iptables active in the .conf file causes the firewall step to be skipped.  All blocking happens using the txt files where we set the blocked hosts in and in the /etc/hosts.deny file.

**Comment by ZerooCool** [comment]
But precisely, I wanted to check if iptables was active or not, by default, because during my reading, when I made the configuration file as an example, I seemed to read that by default, iptables is activated in the configuration .

So, if iptables is enabled by default in the configuration, then iptables is a prerequisite.
Or, you must disable iptables from the default configuration.

Or am I wrong, and, iptables is not enabled by default in the configuration?

Finally, I had read a note on Ubuntu, somewhere, which said that the TCP Wrapper mechanism used by DenyHosts could no longer work following updates, and, I do not know enough about that, it is a note that I saw pass, quickly, I am not even sure that it is actually consistent.
If you have an idea about it.

**Comment by josev814** [comment]
In that case, you can mark it as a pre-requisite.

I know there's an open bug about the possibility of using other firewalls, but I haven't looked extensively into it.  We do have pf tables support for open BSD. That is only ran if the PT_TABLE setting is set in the config though.

So, iptables would be considered a pre-requisite for most operating systems, but for BSD it's not, and the config should be updated for PF Tables.  I'm pretty sure in the Wiki it says about that somewhere.

Regarding the Ubuntu TCP wrapper bug, I'd need a link to the discussion to see what they're referencing.

**Comment by ZerooCool** [comment]
Ok : for BSD it's not, and the config should be updated for PF Tables.
I don't no. I don't use BSD.

For me, it's ok with Iptables. Up documentation #188 

I open a new issue for ' Is there a problem with TCP wrapper and Ubuntu ' #189

Issue closed for Iptables prerequisite.
