### ISSUE TITLE
drop of libwrap from openssh

### ISSUE THREAD

**Issue by gartim** [denyhosts/denyhosts#17]
is there other options denyhosts can use, looks like openssh is dropping support of /etc/hosts.deny, /etc/hosts.allow (libwrap).

**Comment by slicer69** [comment]
Recent versions of DenyHosts can block connections using IPTables (Linux) and the PF packet filter (BSD). There is no need to rely on /etc/hosts.deny

**Comment by gartim** [comment]
okay, that great...been using swatch (perl mod) to do in a less elegant way
the same thing...thanks...Is there a good writeup to switching between
hosts.deny and iptables?

**Comment by slicer69** [comment]
For most people it is really straight forward. Assuming you have the latest version of DenyHosts installed, just make sure the line

IPTABLES = /sbin/iptables

exists somewhere in your configuration file. The default location of the configuration file is /etc/denyhosts.conf

Actually, if you install the latest version of DenyHosts, I think IPTables support might be enabled by default on Linux machines. The path /sbin/iptables is the location of the iptables command. I think the program is usually stored in /sbin, but if your distribution installs iptables in a different location, change the line in the configuration file to match the location of the iptables program.

**Comment by gartim** [comment]
will test out shortly thanks much!
