### ISSUE TITLE
SYNC_VERSION not defaulting to a state

### ISSUE THREAD

**Issue by bigwavedave42** [denyhosts/denyhosts#179]
I updated my Python2 client to master
`Updating c48d30f..ebb1564`

When restarting it gave an error.
INFO:prefs:   WORK_DIR: [/var/lib/denyhosts]
Traceback (most recent call last):
  File "/usr/bin/denyhosts.py", line 174, in <module>
    if prefs.get('SYNC_SERVER') and (is_true(prefs.get('SYNC_VERSION')) or prefs.get('SYNC_VERSION') is None):
  File "/usr/lib/python2.7/site-packages/DenyHosts/prefs.py", line 216, in get
    return self.__data[name]
KeyError: 'SYNC_VERSION

Checking the new conf file that got pushed, it says:
` SYNC_VERSION: whether to sync your python and denyhosts version to the sync server
 The default is yes.`

However, that doesn't seem to be the case, as the daemon wouldn't start in this state.  I added:
`SYNC_VERSION = yes`
and the daemon was able to start.

**Comment by josev814** [comment]
I had to add SYNC_VERSION to the prefs init.  I was thinking that if an item wasn't found in the config that it defaulted to None, but that's not the case.  I have a patch for the issue.  Just waiting for unit tests to pass before merging it.

**Comment by josev814** [comment]
@bigwavedave42 The patch is merged in and should be good now

**Comment by bigwavedave42** [comment]
tried the new master AND removed the line from my config...

I'm now getting a new error:
Traceback (most recent call last):
  File "/usr/bin/denyhosts.py", line 174, in <module>
    if prefs.get('SYNC_SERVER') and (is_true(prefs.get('SYNC_VERSION')) or prefs.get('SYNC_VERSION') is None):
  File "/usr/lib/python2.7/site-packages/DenyHosts/util.py", line 65, in is_true
    return s.lower() in ('1', 't', 'true', 'y', 'yes')
AttributeError: 'NoneType' object has no attribute 'lower'

It doesn't allow the daemon to start.

Adding the value back to config file allows it to start again.  So, it seems like there is a new problem, or it at least moved.

**Comment by josev814** [comment]
I had to move the check of none to before checking the is_true check

**Comment by bigwavedave42** [comment]
That seems to have fixed the error on my system!  Thanks!
