### ISSUE TITLE
Disappearance of Denyhosts 2.10.2 from the SID version of Debian

### ISSUE THREAD

**Issue by ZerooCool** [denyhosts/denyhosts#191]
Disappearance of Denyhosts 2.10.2 from the SID version of Debian, but, no additional information following this withdrawal.

https://packages.debian.org/search?suite=sid&keywords=denyhosts

**Comment by josev814** [comment]
I was able to find it on snapshots, but it's version 10.

http://snapshot.debian.org/archive/debian-archive/20160313T130328Z/debian/pool/main/d/denyhosts/

**Comment by josev814** [comment]
I found additional versions of denyhosts in snapshots. 
 http://snapshot.debian.org/package/denyhosts/

**Comment by ZerooCool** [comment]
Ok thank you i add that to my wiki.

Do you have any idea if the 3.x package can be integrated?
Do you still have serious problems concerning the problems identified for Debian?

**Comment by janpascal** [comment]
The reason is Decided is getting rid of Python 2, which the old package still depends on.

Zer00CooL <notifications@github.com> schreef op 16 juni 2020 13:29:32 CEST:
>Disappearance of Denyhosts 2.10.2 from the SID version of Debian, but,
>no additional information following this withdrawal.
>
>https://packages.debian.org/search?suite=sid&keywords=denyhosts
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/denyhosts/denyhosts/issues/191

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by ZerooCool** [comment]
Ha ok. bye bye python 2.
