### ISSUE TITLE
No package support for Ubuntu 20.04?

### ISSUE THREAD

**Issue by vguna** [denyhosts/denyhosts#213]
Hey,
I just stumbled across the fact, that denyhosts was dropped from focal release :,-(. Is there any reason why is that?

**Comment by qs5779** [comment]
I never realize it was part of focal, when I read this a couple of days ago I was in the process of creating packages for buster, focal and impish. I am not suggesting, but and offering ... the python3-denyhosts packages for the dist code name I mentioned are in the testing component of my repo at https://apt.wtforg.net.

**Comment by vguna** [comment]
Hey, sorry maybe I was not clear enough, I meant it didn't make it into focal :). It was [part of bionic as it seems](https://packages.ubuntu.com/search?keywords=denyhosts&searchon=names&suite=all&section=all). So I was surprised why it is not part of focal. But anyway thanks for the pointers to your repo - that should do the trick :D!
