### ISSUE TITLE
Denyhosts failed to start after update from bullseye to bookworm

### ISSUE THREAD

**Issue by sleeplessaa** [denyhosts/denyhosts#226]
### Description

When I'm used denyhosts 3.1 under Raspbian GNU/Linux 11 / bullseye
and start the script via systemd 
there was no issues. 
All works fine as expected.

But after an update from bullseye to bookworm,
denyhosts failed to start with error : 

 denyhosts.py --daemon --config=/etc/denyhosts.conf
Traceback (most recent call last):
  File "/usr/sbin/denyhosts.py", line 18, in <module>
    from DenyHosts.deny_hosts import DenyHosts
  File "/usr/share/denyhosts/DenyHosts/deny_hosts.py", line 24, in <module>
    from .sync import Sync
  File "/usr/share/denyhosts/DenyHosts/sync.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

DENYHOSTS version 3.1

Any idea how I can fix that ? 

### DenyHosts Version

3.1

### Reproduction steps

```bash
denyhosts.service - SSH log watcher
     Loaded: loaded (/etc/systemd/system/denyhosts.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-09-26 22:40:12 +03; 25min ago
    Process: 6312 ExecStartPre=/bin/rm -f /run/denyhosts.pid (code=exited, status=0/SUCCESS)
    Process: 6313 ExecStart=/usr/sbin/denyhosts.py --daemon --config=/etc/denyhosts.conf (code=exite>
        CPU: 1.413s

Sep 26 22:40:12  denyhosts.py[6313]:     from DenyHosts.deny_hosts import DenyHosts
Sep 26 22:40:12  denyhosts.py[6313]:   File "/usr/share/denyhosts/DenyHosts/deny_hosts.py", lin>
Sep 26 22:40:12  denyhosts.py[6313]:     from .sync import Sync
Sep 26 22:40:12  denyhosts.py[6313]:   File "/usr/share/denyhosts/DenyHosts/sync.py", line 6, i>
Sep 26 22:40:12  denyhosts.py[6313]:     import requests
Sep 26 22:40:12  denyhosts.py[6313]: ModuleNotFoundError: No module named 'requests'
Sep 26 22:40:12  systemd[1]: denyhosts.service: Control process exited, code=exited, status=1/F>
Sep 26 22:40:12  systemd[1]: denyhosts.service: Failed with result 'exit-code'.
Sep 26 22:40:12  systemd[1]: Failed to start denyhosts.service - SSH log watcher.
Sep 26 22:40:12  systemd[1]: denyhosts.service: Consumed 1.413s CPU time.
```

### OS

Raspbian GNU/Linux 12

**Comment by josev814** [comment]
Can you run python3 -m pip freeze and post the results?  I think you'll need to run python3 -m pip install requests to fix the issue, which I'm surprised isn't already installed.

**Comment by sleeplessaa** [comment]
apt-get install python3-requests solve the problem.

Thanks for your help.

**Comment by josev814** [comment]
I'm going to close this issue since it's resolved.  Additionally, I spun up a base Debian 12 image, and the only thing of note in the install process was that I have to install python3-pip before running the installer.  Once I did that, the application was able to install without any issues.
