### ISSUE TITLE
Upcoming 2.10 release

### ISSUE THREAD

**Issue by slicer69** [denyhosts/denyhosts#25]
I want to push out a new release, version 2.10, sometime next week. This will incorporate all the bug fixes to date, plus include all the work done to merge the various code bases and patches. I want to get this release done before we tackle IPv6, reading systemd logs and ipset.

If there is anything crtiical you feel needs to go into 2.10, please let me know soon so we can merge it and get it done before I take a snapshot and post a new release.

**Comment by jasontibbitts** [comment]
I'm patching a few things for Fedora currently (and I'm not quite done) but if you're planning to release next week there's little chance I could get 2.9 pushed out before then in any case.

Unfortunately I'm just about to leave town and won't be able to do anything before Monday, but I do have a couple more pull requests to generate.  No big deal if they don't make the release, though.

**Comment by slicer69** [comment]
I don't mind holding off an additional week for additional bug fixes. What if we aim for Feb 15th as the release date, does that give enough of a window?

**Comment by jasontibbitts** [comment]
It's really no bid deal, because I can just patch the Fedora package as needed.  Feel free to release whenever you like.  The 15th should be as good for me as any other date.  (Though luckily I'll be busy on the 14th....)

**Comment by slicer69** [comment]
Fair enough. And congratulations on being busy on the 14th.

**Comment by slicer69** [comment]
The 2.10 release has been packaged and uploaded. Now we can look forward to merging some experimental features.

**Comment by jasontibbitts** [comment]
Could someone create the 2.10 release in github?

I added denyhosts to Anitya (release-monitoring.org) but I pointed it at github for determining the latest release, and github only shows 2.9.  Anitya does nice things like automatically file bugs when new versions appear, and automatically does scratch builds of updates.

Alternately I could switch the upstream to sourceforge.  I think Anitya can parse the files section there as well.  I'm just not sure which of github or denyhost.sf.net is supposed to be canonical.

**Comment by jasontibbitts** [comment]
Oh, and thanks for the kind note in the release announcement.

**Comment by slicer69** [comment]
I have create a GitHub release: https://github.com/denyhosts/denyhosts/releases

**Comment by dk-dkopen** [comment]
@slicer69 good stuff - thanks!
(sorry, I had zero badwidth lately to actively participate lately, but i'm still interested and keeping an eye)

**Comment by slicer69** [comment]
No problem, life has a way of getting in the way of coding projects. If you have a chance, please try out the ipset code and see if it works okay for you. I'm hoping to test it myself soon, but (again) life keeps interfering.
