### ISSUE TITLE
Odd patch Fedora is carrying

### ISSUE THREAD

**Issue by jasontibbitts** [denyhosts/denyhosts#28]
As of the 2.10 release, Fedora is carrying only one patch (besides the one that switches the config settings over to the ones Fedora needs, of course).  That patch patch follows:
````diff
--- denyhosts.py.orig   2015-02-04 17:05:25.480851887 -0600
+++ denyhosts.py        2015-02-04 17:07:38.155738253 -0600
@@ -18,6 +18,7 @@
 from DenyHosts.constants import *
 from DenyHosts.sync import Sync

+info = logging.getLogger("denyhosts").info
 #################################################################################


@@ -232,6 +233,8 @@
                     info("received new hosts: %s", str(new_hosts))
                     sync.get_denied_hosts()
                     sync.update_hosts_deny(new_hosts)
+                    dh.get_denied_hosts()
+                    dh.update_hosts_deny(new_hosts)
             sync.xmlrpc_disconnect()
         except Exception, e:
             lock_file.remove()
````

I can't remember why I have that patch at all.  I added it way back in Fedora 11:

* Fri Nov 07 2008 Jason L Tibbitts III <tibbs@math.uh.edu> - 2.6-14
- Add patch from upstream to fix command line --sync.

but after all this time I have no idea if it's still remotely relevant.  I think it came from this thread http://sourceforge.net/p/denyhosts/mailman/denyhosts-user/thread/Pine.LNX.4.64.0811071024250.22653@mailzilla.net/ and I guess those changes just got lost.

**Comment by slicer69** [comment]
I'll add it into my tree.

**Comment by jasontibbitts** [comment]
Oh, cool, I was just making a pull request.

**Comment by slicer69** [comment]
Merged it into my tree.
