### ISSUE TITLE
NameError: name 'logging' is not defined

### ISSUE THREAD

**Issue by jasontibbitts** [denyhosts/denyhosts#31]
Oops.  Right at the top of denyhosts.py

info = logging.getLogger("denyhosts").info

but there's no import of logging.  Not sure how that slipped by.

**Comment by slicer69** [comment]
It doesn't seem to be needed, but I'm going to add the import logging statement in the denyhosts.py file, just so it looks all nice and proper.

**Comment by jasontibbitts** [comment]
Hmm, not sure how it's not needed.  At least I get a fail on startup without it.

**Comment by jasontibbitts** [comment]
So I was a bit confused.  The 2.9 version had some extra imports up there, and when that patch for command line sync was added port 2.10 it added the logging line.  So 2.10 was OK and things only broke because I didn't properly test the command line patch against it.

**Comment by slicer69** [comment]
I think this is fixed now in the master branch. Will test it out and close this issue if everything works.
