### ISSUE TITLE
Sync server

### ISSUE THREAD

**Issue by jasontibbitts** [denyhosts/denyhosts#35]
One of the things that always bugged me about denyhosts is that the sync server was non-free.  (And lately I'm not sure if it's even working; I didn't use it in any case.)

It looks like someone mocked up a sync server as part of the test suite, but has anyone (besides me, I guess) considered actually reimplementing it?

**Comment by janpascal** [comment]
Hi, 

I've tried my hand at implementing an open source
denyhosts sync server. You can find the source on github[1]. It's
interoperable with denyhosts now, but can be improved a lot in security,
logging, documentation etc. The deamon is in Python with the Twisted
framework (chosen because its xmlrpc library supports calling the rpc
functions with the HTTP request as a parameter, needed for the client IP
address). I'm using the Twistar ORM framework, which works nicely with
Twisted. Twisted is an asynchronous web framework, written for high-volume
servers which I expect will be needed for this project.

I'm looking for feedback on the sync server code. I could run an
instance on a private server so a few users could test it. Later on, there
will probably be a need for a hosted server somehow to cope with the load.

I'd be happy with any feedback!

Cheers

Jan-Pascal

[1] https://github.com/janpascal/denyhosts_sync
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=622697

**Comment by slicer69** [comment]
I like this idea. Will the sync server work with our current version of DenyHosts without any modification? I'm definitely interested in trying it out.
Also, if the sync server works well, I would be open to hosting it as a public service. I've got a server that is not doing much at the moment.

**Comment by janpascal** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hi Jesse,

The current server should work for denyhosts 2.10 without modifications.
It's certainly not ready yet for production use, but of course you can
try. Could you send me the IP address(es) you'll be connecting from by
private mail to janpascal@vanbest.org? I'll open up the firewall for you.

Cheers

Jan-Pascal

On 06/21/2015 08:56 PM, Jesse Smith wrote:
>
> I like this idea. Will the sync server work with our current version
of DenyHosts without any modification? I'm definitely interested in
trying it out.
> Also, if the sync server works well, I would be open to hosting it as
a public service. I've got a server that is not doing much at the moment.
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/denyhosts/denyhosts/issues/35#issuecomment-113941484>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBCAAGBQJVhwu9AAoJEPgwem7WkKwGleAQAJcpjxWtohJ4fDdeHpeqYWQB
jdSRkoRkgNEgvl9PTcLinOw1YZddYkEprMdbn00SzRCGtMKP129JZom1lpQFZixr
VPxBU5fzYY6zLblqMI8ylyFm+EjGtYRL5I+XDMs5+qaj6tE1n8o/QGdiJ3TJ3n0I
DNUDFGvPW1t6oUZqtxr2Z9cVCaAcRARlJVrJ9tdfbkzz/d9n1syIbix32RLfOJjn
qRtmUAv7hGWpkkuR9MfdMPbSu0bE509+tGLCJbH0UAy00t586A8J/abrO9zxodZV
hqM85WF9H3Mlt++oe6jjq+jOJtalw2QaNiFdaMhoZtSk4rnkER5WymoBJYcsxE+k
Wm6mBfA8UAk3oCf3dRsDigy2sZez9ag9KpNDfmr2vlFsubD0ME7bfuPGKO+wGk10
jDQDnpOK83YjXIiLjfEBbCZsfVo0g3oF7vGTjD6Pkve49LXLhee6DZGyRvt6CF8w
l3WI+EF5wjV5ZmIFjB4ipQwp661sK0aTb+Tw7Noo28Zm5OM2ATaIyCHhMxhTvk2/
kvVx/AgiGpaMbAp/7hyrxcx1iENt0kiSnAeZVpP1X8pReywL7jixBF5coog70LfQ
jtmZ44KIy+ayBAMp08/V7Gti5tN0nT+OL+DsIe5Bg2owrs8qZvgVklXhUSJdRr8g
7WILsYI8/5GBDwoHUfCh
=kT7/
-----END PGP SIGNATURE-----

**Comment by janpascal** [comment]
Talking about the current sync protocol, there's a strange parameter to the get_new_hosts rpc call with (presumably) the last list of hosts sent to the sync server. It's completely ignored by my implementation as I don't have a clue what to do with it.

Jan-Pascal

**Comment by slicer69** [comment]
I could be mistaked, but I think the hosts_added parameter in the get_new_hosts function is there to let the sync server know what the client got last time. It's a method to make sure the server does not send duplicate messages, if I'm not mistaken. That way if the server plans to send 1.2.3.4 and 5.6.7.8, but the client says we already have 1.2.3.4, then the server can trim that address out and send only 5.6.7.8. Ideally it should reduce the amount of bandwidth required by both sides since the server avoids sending uncessary data.

**Comment by janpascal** [comment]
No, in line 113 of sync.php it sends self.__hosts_added, which is set in line 80 after new hosts have been sent to the sync server. Maybe it's a way of preventing, as a client, to get sent back the exact list of hosts you've just sent to the sync server?

**Comment by jasontibbitts** [comment]
In case this gets off the ground, I have some handy server hardware around as well.  I can allocate VMs or if necessary I can pull together full machines.

**Comment by slicer69** [comment]
I'm getting 404 errors in my denyhosts log file when trying to connect to the test server. Not sure if it is on my end or the server side. This is when using DenyHosts's current "master" branch, which should be about the same as DenyHosts 2.10.

**Comment by slicer69** [comment]
With many thanks due to Jan-Pascal for writing the code and helping trouble-shoot my issues, I have set up the sync server on a test machine. So far it appears to be working. If anyone would like to connect to the server and help test it, the address of the sync server is:
deny.resonatingmedia.com:9911

Right now there are no addresses in my sync server's test database so maybe we can get some DenyHosts clients connected to fill it up with new addresses?

**Comment by janpascal** [comment]
Just switched my denyhosts config to sync to your server. Let's fill 'r up!

**Comment by xrat** [comment]
Running denyhosts 2.6 on Debian Wheezy, we switched to this server on July 16. Since the morning of July 19 (timezone +0200), we repeatedly see the following error:
```
2015-07-19 08:33:35,723 - denyfileutil: INFO     num entries purged: 3
2015-07-19 08:35:39,435 - sync        : ERROR    <Fault 8002: 'error'>
Traceback (most recent call last):
  File "/usr/share/denyhosts/DenyHosts/sync.py", line 117, in receive_new_hosts
    self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 8002: 'error'>
2015-07-19 09:06:32,381 - sync        : INFO     received 0 new hosts
```
Is the new server supposed to work with old Denyhosts installations?

**Comment by janpascal** [comment]
Yes, it is. Could it be your denyhosts daemon is trying to feed an illegal IP address to the sync server? I'll post a patch soon that will print the actual XML-RPC error messsages to the log file, those should clarify things

**Comment by xrat** [comment]
I thought it was rather the other way round: Since the error occurs in `receive_new_hosts` I thought the server is maybe sending something the client can't handle. However, I couldn't find "Fault 8002" in the client code, either.
Anyway, sync'ing always worked with http://xmlrpc.denyhosts.net:9911 except from timeouts. I've now also cleanup `/etc/hosts.denyhosts` and removed `/var/lib/denyhosts/sync-received` but the error persists.
Looking forward to your XML-RPC error messages.

**Comment by janpascal** [comment]
Hi, the below patch to denyhosts catches Fault-type exceptions when accessing the xmlrpc sync server and prints the error message received from the server. It may help debugging xrat's issues

```
--- sync.py	2015-07-20 20:32:01.384145102 +0200
+++ /home/janpascal/sync.py	2015-07-20 19:37:26.791619958 +0200
@@ -1,13 +1,14 @@
 import logging
 import os
 import time
+import xmlrpclib
 from xmlrpclib import ServerProxy, Transport
 from httplib import HTTP
 
 from constants import SYNC_TIMESTAMP, SYNC_HOSTS, SYNC_HOSTS_TMP, SYNC_RECEIVED_HOSTS
 
 logger = logging.getLogger("sync")
-debug, info, error, exception = logger.debug, logger.info, logger.error, logger.exception
+debug, info, warning, error, exception = logger.debug, logger.info, logger.warning, logger.error, logger.exception
 
 def get_plural(items):
     if len(items) != 1:
@@ -118,6 +119,8 @@
 
         try:
             self.__server.add_hosts(hosts)
+        except xmlrpclib.Fault as err:
+	    warning("RPC error received, error {} ({})".format(err.faultCode, err.faultString))
         except Exception, e:
             exception(e)
 
@@ -140,6 +143,9 @@
             info("received %d new host%s", len(hosts), get_plural(hosts))
             self.__save_received_hosts(hosts, timestamp)
             return hosts
+        except xmlrpclib.Fault as err:
+	    warning("RPC error received, error {} ({})".format(err.faultCode, err.faultString))
+	    return None
         except Exception, e:
             exception(e)
             return None

```

**Comment by janpascal** [comment]
Oh, and the denyhosts clients also sends a list of IP addresses when calling receive_new_hosts. It sends the last list of addresses it sent to the server before, presumably to prevent getting the same set back from the server.

**Comment by ingber** [comment]
In the latest version I see:
SYNC_SERVER = http://deny.resonatingmedia.com:9911
testing this:
http://deny.resonatingmedia.com/
gives:
It works!
However,
http://deny.resonatingmedia.com:9911/
gives:
Method Not Allowed 
Your browser approached me (at /) with the method "GET". I only allow the method POST here.

I get no downloads.

**Comment by slicer69** [comment]
I think you might need to remove the trailing "/" character in the URL. So the SYNC_SERVER value would be http://deny.resonatingmedia.com:9911

**Comment by ingber** [comment]
My typo.  I did not have a trailing "/".  Try it in your browser:
http://deny.resonatingmedia.com:9911

I get:
Method Not Allowed

Your browser approached me (at /) with the method "GET". I only allow the method POST here.

**Comment by slicer69** [comment]
If you are trying to access the sync server in a browser it will not work. The sync server will reject GET requirests (from the browser) as it is waiting to receive specific commands from the DenyHosts software.

or have I misunderstood and you are seeing this information in your DenyHosts output?

**Comment by ingber** [comment]
I do not think I should be getting this message.  I tested this after seeing failures in my /var/log/denyhosts file:
... global name 'ServerProxy' is not defined

I'll try turning on this SYNC_SERVER again (3rd time trying this, since we know sf.net 's http://xmlrpc.denyhosts.net:9911 is down now).

**Comment by slicer69** [comment]
Sorry if you posted this and I missed it, which version of DenyHosts are you running? I think the ServerProxy variable was removed in recent versions.

**Comment by ingber** [comment]
I just installed the latest commit of 3.0.
~# denyhosts.py --version
('DenyHosts version:', '3.0')





 Prof. Lester Ingber
 lester@ingber.com  ingber@alumni.caltech.edu
​ [image: http://www.ingber.com] <http://www.ingber.com/>
  [image: http://alumni.caltech.edu/~ingber]
<http://alumni.caltech.edu/~ingber>  [image:
http://www.linkedin.com/in/ingber] <http://www.linkedin.com/in/ingber>  [image:
http://google.com/+LesterIngber] <http://google.com/+LesterIngber>  [image:
http://www.facebook.com/lester.ingber]
<http://www.facebook.com/lester.ingber>  [image: http://twitter.com/ingber]
<http://twitter.com/ingber>

**Comment by ingber** [comment]
Sorry about the sig line; I replied via email.

**Comment by ingber** [comment]
Yep, after
service denyhosts restart
I see:
Jul 20 16:21:35 - sync        : ERROR    global name 'ServerProxy' is not defined
Jul 20 16:21:35 - sync        : ERROR    Could not initiate xmlrpc connection

even though I'm using the nre server?  Just above these entries I have:
Jul 20 15:21:32 - prefs       : INFO        SYNC_SERVER: [http://deny.resonatingmedia.com:9911]

**Comment by ingber** [comment]
I will go back to
http://xmlrpc.denyhosts.net:9911
and restart the service.  sf.net has to come up sometime ....

**Comment by janpascal** [comment]
Which Python version are you using, Python 2.7 or Python 3? There is
some strange code in the beginning of sync.py that seems only to import
ServerProxy on Python3, but it is still using ServerProxy regardless of
the Python version.

@Jesse, could this be a bug for Python2?

Jan-Pascal

**Comment by xrat** [comment]
@ingber AFAIK, xmlrpc.denyhosts.net is not hosted by soureforge.net, and it is working relatively OK apart from frequent timeouts.

**Comment by xrat** [comment]
@janpascal Could not apply your patch directly, guess my denyhosts' `sync.py` is too old. But selective copy-pase+s/warning/info/ did it. Here is an excerpt with the patch applied (UTC+0200):
```
2015-07-21 11:55:19,939 - denyhosts   : INFO     sync_time:      : 420
2015-07-21 11:55:19,939 - denyhosts   : INFO     sync_sleep_ratio: 6
2015-07-21 12:01:29,229 - sync        : INFO     RPC error received, error 8002 (error)
2015-07-21 12:07:39,669 - sync        : INFO     received 0 new hosts
2015-07-21 12:13:50,288 - sync        : INFO     received 0 new hosts
```

**Comment by janpascal** [comment]
Hi, the 8002 errors are something from the sync server that Jesse and I are working on.

**Comment by ingber** [comment]
http://xmlrpc.denyhosts.net:9911 is working now.
I will try http://deny.resonatingmedia.com:9911 .

**Comment by janpascal** [comment]
Sounds good. You will probably get intermittent 8002 error messages, we're working on what is causing them. You can ignore them for now. 

Kind regards 

Jan-Pascal 

On July 21, 2015 8:12:37 PM GMT+02:00, Lester Ingber <notifications@github.com> wrote:
>http://xmlrpc.denyhosts.net:9911 is working now.
>I will try http://deny.resonatingmedia.com:9911 .
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/denyhosts/denyhosts/issues/35#issuecomment-123420757

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ingber** [comment]
My perviosu two reports from http://xmlrpc.denyhosts.net:9911 gave me two downloads.  After changing servers and restarting, my first report from http://deny.resonatingmedia.com:9911 shows:

Jul 21 12:01:02 - denyfileutil: INFO     purging entries older than: Tue Jun 16 12:01:02 2015
Jul 21 12:01:02 - denyfileutil: INFO     num entries purged: 0
Jul 21 12:01:03 - sync        : INFO     received 0 new hosts

**Comment by ingber** [comment]
Twice more using http://deny.resonatingmedia.com:9911 I got
Jul 21 12:01:03 - sync : INFO received 0 new hosts
I went back to  http://xmlrpc.denyhosts.net:9911 and now I'm getting regular hourly updates.

**Comment by janpascal** [comment]
Shouldn't this issue be closed?

**Comment by slicer69** [comment]
Yep, closing.
