### ISSUE TITLE
Persistent IPTABLES rules

### ISSUE THREAD

**Issue by slicer69** [denyhosts/denyhosts#37]
We make PF firewall rules persistent across reboots. Some people using IPTABLES as their firewall have asked that IPTABLES rules also survive a reboot.

**Comment by ingber** [comment]
I'm using the iptables option.  So, after getting 4000+ IPs from the SYNC_SERVER, with 4000+ entries active in /etc/hosts.deny, after a reboot, I see zero (0) entries in my iptables list from denyhosts.  Are these now simply worthless?

Is there some script to run at boot that comes with denyhosts to at least repopulate iptables with the current entries in hosts.deny?

**Comment by josev814** [comment]
Closing this, since it's the same as Bug #46
