### ISSUE TITLE
Problem when try no start manual

### ISSUE THREAD

**Issue by pierrejochem** [denyhosts/denyhosts#39]
OS: Ubuntu 14.04 LTS

Deny Host Version: 3.0

Installation via: python setup.py install

**/usr/local/bin/denyhosts.py --config /etc/denyhosts.conf --daemon**

```
Traceback (most recent call last):
  File "/usr/local/bin/denyhosts.py", line 229, in <module>
    first_time, noemail, daemon, foreground)
  File "/usr/local/lib/python2.7/dist-packages/DenyHosts/deny_hosts.py", line 77, in __init__
    offset = self.process_log(logfile, last_offset)
  File "/usr/local/lib/python2.7/dist-packages/DenyHosts/deny_hosts.py", line 488, in process_log
    self.__report.add_section(msg, new_denied_hosts)
  File "/usr/local/lib/python2.7/dist-packages/DenyHosts/report.py", line 41, in add_section
    if type(i) in (TupleType, ListType):
NameError: global name 'TupleType' is not defined
```

Any ideas?

**Comment by slicer69** [comment]
It looks like you're using the pre-release version of v3.0 from GitHub where this is a known bug. If you install the latest snapshot of DenyHosts from github or from the project's website, then you will find this has been fixed.

**Comment by pierrejochem** [comment]
I have used this download:

https://github.com/denyhosts/denyhosts/archive/v3.0.zip

**Comment by pierrejochem** [comment]
Where is the fixed Version available?

**Comment by slicer69** [comment]
You could download the 2.10 version if you want a tarball. Or, if you're comfortable using git, then you can run
git clone https://github.com/denyhosts/denyhosts.git
That'll download the latest version that has the fix.

**Comment by pierrejochem** [comment]
Thank you!
