### ISSUE TITLE
Problem when running with Python 2.7

### ISSUE THREAD

**Issue by janpascal** [denyhosts/denyhosts#40]
Gives error messages like this when trying to sync:
2015-07-27 06:27:16,622 - sync        : ERROR    global name 'ServerProxy' is not defined
2015-07-27 06:27:16,623 - sync        : ERROR    Could not initiate xmlrpc connection
Waiting for data... (interrupt to abort)

 The fix is to replace line 7 op sync py with
from xmlrpclib import ServerProxy

It's weird you didn't catch this with the unit tests, did you run them with Python 2?

**Comment by slicer69** [comment]
This was actually fixed around a month ago. It's only an issue for people using the v3.0 pre-release snapshot. People using the latest code from GitHub or who download the tarball from our website will have the fixed version.

**Comment by janpascal** [comment]
I'm still experiencing these issues with the latest github commit, and certainly with 3.0 release. Running
`python -m unittest discover` find some issues, both with python 2 and with python 3. Would you like me to prepare a patch for the issues in sync.py?

**Comment by janpascal** [comment]
See the pull request I just created

**Comment by slicer69** [comment]
I have merged this patch. Thank you.
