### ISSUE TITLE
Parse attacks on dovecot imap server from logs

### ISSUE THREAD

**Issue by janpascal** [denyhosts/denyhosts#44]
On one of my servers running the dovecot IMAP server, I'm using the following regex in denyhosts.conf to detect (and block) brute forcing of email passwords.

USERDEF_FAILED_ENTRY_REGEX=dovecot.*authentication failure.*ruser=(?P<user>\S+).*rhost=(?P<host>\S+).*

Would this rule have a place in the denyhosts standard installation, maybe as an option, e.g. DETECT_DOVECOTE_IMAP_LOGIN_ATTACKS?

Jan-Pascal

**Comment by slicer69** [comment]
I would certainly see this as a nice option to have, perhaps turned off by default.

If I'm not mistaken, the regex rule above should work for pop3 as well as imap connections, wouldn't it? Maybe we could add an option to the config file simply called "BLOCK_DOVECOT_ATTACKS"?

**Comment by janpascal** [comment]
Thanks. It's on by default now, I think we said it shouldn't be? 

On September 16, 2015 9:33:19 PM GMT+02:00, Jesse Smith <notifications@github.com> wrote:
>Closed #44 via cdcbb45fd69bdfdfd1646b9d9a9b9af3913f4e03.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/denyhosts/denyhosts/issues/44#event-411366219

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by slicer69** [comment]
It's off by default.
