### ISSUE TITLE
Entries created in hosts-restricted despite no restricted-usernames file

### ISSUE THREAD

**Issue by dansut** [denyhosts/denyhosts#48]
The documentation seems to suggest that if there is no `restricted-usernames` file then the `hosts-restricted` should be empty. This does not seem to be the case as entries appear to be added to this file for every host that ever accesses the server.

Further investigations suggest that these _unneeded_ entries always have a zero count and so never really have an effect but it does mean this file will grow very large needlessly and work is being done where it doesn't need to be. Brief overview of the sources suggest it could be `AGE_RESET_` related  actions that cause this and that `hosts-restricted` is perhaps not the only _hosts*_ file affected.

Behavior noted for 3.0 installation on EL6 (python2.6).

Also see this [ServerFault Q&A](http://serverfault.com/q/647153/310481) for more evidence of others noting this and further details.

**Comment by slicer69** [comment]
I think I have fixed this in the "restricted" branch here on GitHub. If anyone wants to test it and confirm the patch works, I'll commit it to the next release.

**Comment by dansut** [comment]
Thought I'd get in just before my original report was a year old.

Tried your patch, seems to do what you intended to without any bad side effects.

I still think there's a a more efficient general fix here so as not to bother writing entries in files with zero entries, but this is a good start - roll it into the next release.

Cheers
