### ISSUE TITLE
sync-server ERROR

### ISSUE THREAD

**Issue by ILMostro** [denyhosts/denyhosts#49]
running denyhosts in daemon-mode or via commandline, after stopping daemon, results in ERROR in CentOS7:

```
Oct 16 15:09:31 - prefs       : INFO        WORK_DIR: [/var/lib/denyhosts]
Oct 16 15:09:31 - denyhosts   : INFO     restricted: set([])
Oct 16 15:09:31 - denyhosts   : INFO     Log file size has not changed.  Nothing to do.
Oct 16 15:09:31 - sync        : ERROR    'SYNC_PROXY_SERVER'
Oct 16 15:09:31 - sync        : ERROR    Could not initiate xmlrpc connection
```

**Comment by slicer69** [comment]
What is the sync server's address set to in your configuration file?

**Comment by ILMostro** [comment]
the default: 
```
SYNC_SERVER = http://xmlrpc.denyhosts.net:9911
```

**Comment by slicer69** [comment]
That was the old project's sync server, I don't think they maintain it anymore. This project uses http://deny.resonatingmedia.com:9911

**Comment by ILMostro** [comment]
I guess I misunderstood the discussion in your [Issue 35](https://github.com/denyhosts/denyhosts/issues/35).  Judging by the last guy's response to "go back to" previous sync server, I thought the newer server you guys were working on didn't work.

**Comment by ILMostro** [comment]
BTW: I get the same error with the new server as well

**Comment by slicer69** [comment]
Which version of DenyHosts are you running?

**Comment by ILMostro** [comment]
```
# rpm -q denyhosts
denyhosts-2.9-4.el7.noarch
```

**Comment by slicer69** [comment]
In that case I would suggest downloading the latest version (v3.0) from here: http://denyhost.sourceforge.net/download.php

I think there may be some compatibility issues between the older EL package and the sync server.

**Comment by jasontibbitts** [comment]
I guess I'll need to push 3.0 to el7 at some point.  I think my current Fedora packaging will still build there.  Hmm, or maybe not; crap, the Fedora one is python3 and python3 on EL7 isn't completely there yet.
