### ISSUE TITLE
Single-source Python 2 and 3 support

### ISSUE THREAD

**Issue by mruffalo** [denyhosts/denyhosts#5]
Python 3 is the present and future of the Python language, and this code base needs to run under recent enough versions of 3.x.

Update code to use newer Python idioms and syntax as appropriate.

**Comment by jasontibbitts** [comment]
Just to be sure, it is safe to do string formatting like:

debug("Cursor: {}".format(cursor))

in the current code base?  That's what I'm used to instead of %-type formatting since I usually write entirely in python3, but I don't want to break compatibility prematurely.

**Comment by mruffalo** [comment]
Not quite. As far as I'm concerned the floodgates are now open for dropping support of Python <= 2.5 as per #6, but automatic numbering of string formatting parameters was added in 2.7. That line would have to be
```
debug("Cursor: {0}".format(cursor))
```
to work in 2.6.

I also exclusively use `str.format` instead of the `%` string formatting, and fully support its usage in new code. I'd even consider converting the entire code base, but it's probably better to avoid all of that code churn just for the sake of using newer Python idioms. Enough of the code needs to be updated anyway; may as well just change to use `str.format` whenever we need to touch some code for other reasons.

**Comment by jasontibbitts** [comment]
OK, cool, I'll make sure to number then explicitly.  Thanks.

We could have a flag day at some point and get everything cleaned up, but certainly not until after all of these big projects have been merged.

**Comment by slicer69** [comment]
I have started some work on the transition from Python2 to Python3. I'm testing the code with Python2.7 and Python3.4 at the moment. My porting efforts to Python3 are in the new "py3" branch if anyone wants to look at it.

At the moment the code will run just enough to present a help screen and parse arguments, maybe read the configuration file. However, the code crashes in some places when working with the file system. It seems Python3 is a little more prone to throwing exceptions and crashing if, for example, it tries to create a directory that already exists.

What I'd like to do in the near future is create a separate release brnach of DenyHosts and call it version 3.0. Then, as it becomes stable, merge other work into the 3.0 branch. That way, short term, people running Python 2 can use our 2.x branch and people using Python 3 can run DenyHosts 3.0. Long term we will end up with one branch that should work everywhere.

**Comment by slicer69** [comment]
I believe the transition to Python 3 is now complete. My changes have been pushed to the "py3" branch. Though it is named py3, I have tested the code under both the Python 2.7 and Python 3.4 interpreters. DenyHosts is running on my Debian system with no problems using either Python version.

I am hoping to expand my tests to other platforms this week. Could someone else give the py3 branch a test run and let me know if there are any problems running the code under either Python2 or Python3? I want to make sure the same code works equally well with either version of Python.
