### ISSUE TITLE
Forced reset - how?

### ISSUE THREAD

**Issue by benjaoming** [denyhosts/denyhosts#52]
Thanks for the great project, been using it in previous versions without any issues.

I was perhaps a bit naive, but I followed the instructions for Debian, added the system service, started it... seemed to work.

So I logged out, restarted the server, now I'm locked out.

I guess there are two issues:

 - [ ] What are the instructions to flush iptables, kill the daemon and possibly empty `/etc/hosts.deny` (if that's the file) ?
 - [ ] Somehow the instructions for Debian on Ubuntu 14.04 got me locked out using any remote IP.

I'm willing to assist getting more documentation into this project, but I need assistance understanding it better.

**Comment by benjaoming** [comment]
This is from the FAQ, but seeing lots of mentions of iptables....

```
    Stop DenyHosts
    Remove the IP address from /etc/hosts.deny
    Edit WORK_DIR/hosts and remove the lines containing the IP address. Save the file.
    Edit WORK_DIR/hosts-restricted and remove the lines containing the IP address. Save the file.
    Edit WORK_DIR/hosts-root and remove the lines containing the IP address. Save the file.
    Edit WORK_DIR/hosts-valid and remove the lines containing the IP address. Save the file.
    Edit WORK_DIR/user-hosts and remove the lines containing the IP address. Save the file.
    (optional) Consider adding the IP address to WORK_DIR/allowed-hosts
    Start DenyHosts 
```

I'm wondering if there needs also to be something about flushing iptables, for instance:

   sudo iptables -F

**Comment by slicer69** [comment]
The IPTABLES rules that Denyhosts creates will not survive a reboot at this time, so if you restart the server after purging DenyHosts files you should not have any firewall rules to contend with. We just need to make sure all the IPs of denied hosts have been removed before you reboot.

The above steps should work, but to simplify:
1. Stop DenyHosts
2. Delete /etc/hosts.deny (rm /etc/hosts.deny)
3. Delete any host files from the DenyHosts working folder (usually rm /var/lib/denyhosts/host*)
4. Restart or flush IPTABLES.

That should solve the issue.

**Comment by benjaoming** [comment]
Thanks for this @slicer69 !! I'll try testing out these steps with my provider and get back with a suggestion if there's something that can/should be improved.

**Comment by slicer69** [comment]
Sounds good. Once the issue is ressolved if you can suggest a better way to explain the process in the documentation, please let me know.

**Comment by benjaoming** [comment]
Never got in touch with the provider, got locked out for good.

**Comment by josev814** [comment]
@benjaoming IPTables wasn't flushing a record once it was added even if hosts.deny purged the entry.  I updated this in one of my pushes to make it purge the entry from iptables if it's purged from hosts.deny.
