### ISSUE TITLE
DenyHosts - AttributeError: 'module' object has no attribute 'ListType'

### ISSUE THREAD

**Issue by realnot** [denyhosts/denyhosts#54]
Hi, when I try to run denyhosts I get the error in object. Here the traceback: http://dpaste.com/0BKZNVE

**Comment by realnot** [comment]
Solved, as reported here http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html there's a bug during the porting from python 2.7 to python 3.4. On report.py just change:

`if (type(i) is types.ListType) or (type(i) is types.TupleType):`

with

`if (type(i) is list) or (type(i) is tuple):`

And obviously the import of the module **types** doesn't make sense anymore.

cheers ;-)

**Comment by slicer69** [comment]
Will the new method work on Python 2? The reason it is the way it current shows up is it was the only way I could find to get the code to work on both Python 2 and 3. The error from above looks like the errors I ran into when I ran code compiled for Python 2 through the Python 3 interpreter.

**Comment by realnot** [comment]
No, but you could try with: `if isinstance(i, list) or isinstance(i, tuple)` from https://docs.python.org/3.4/library/functions.html#isinstance Is how should work right?

**Comment by josev814** [comment]
https://github.com/denyhosts/denyhosts/pull/55

This was merged in as of PR #55
