### ISSUE TITLE
Drop support for Python < 2.6

### ISSUE THREAD

**Issue by mruffalo** [denyhosts/denyhosts#6]
#5 will be much easier if we don't have to remain compatible with ancient Python.

**Comment by slicer69** [comment]
dk-dkopen, It would be great if you could test out the py3 branch of DenyHosts and confirm if it works with Python2.6. I have confirm it works with 2.7 and am curious if there are any combatibility conflicts between 2.6 and 2.7.

**Comment by dk-dkopen** [comment]
Sorry, I've been pretty much out of it lately.
I don't have the bandwidth currently to test it extensively with 2.6, and I'm not terribly concerned.
Furthermore, I've been trying to standardize on 2.7 where possible, and I think the differences aren't that great between 2.6 and 2.7
If an issue and a use case is discovered, this can be revisited and fixed as needed.
Thanks!

**Comment by jasontibbitts** [comment]
Well, RHEL6 does have python 2.6, and I need to bring up an EL6 VM so maybe I can try to test some things.  I don't really want to support the denyhosts package in EL6, though.

I still have a big list of denyhosts things to work on; I can toss that one onto the pile.

**Comment by slicer69** [comment]
Right now I think DenyHosts should still work with Python 2.6. If not, we can patch it to work with RHEL 6.
