### ISSUE TITLE
Help, what does this say?

### ISSUE THREAD

**Issue by nottellyou** [denyhosts/denyhosts#63]
[root@localhost denyhosts-master]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in ?
    from DenyHosts.util import normalize_whitespace
  File "/root/denyhosts-master/DenyHosts/util.py", line 11
    from .constants import BSD_STYLE, TIME_SPEC_LOOKUP
         ^
SyntaxError: invalid syntax

when I setup denyhosts on my centos5.6, then this happened.

**Comment by slicer69** [comment]
My guess is the version of Python available on CentOS 5.6 is too old to run DenyHosts. The oldest version of Python I think that has been tested and shown to work is 2.7.9.

**Comment by jasontibbitts** [comment]
>>>>> "JS" == Jesse Smith <notifications@github.com> writes:

JS> My guess is the version of Python available on CentOS 5.6 is too old
JS> to run DenyHosts.

It is; RHEL5 has only python 2.4.3.  Someone could bring in a newer
python via EPEL, but EPEL for RHEL5 will go away in about eight months
anyway.  (Centos5 goes EOL and RHEL5 goes out of production and into
"extended life-cycle support" on March 31, 2017.)  So I doubt anyone
wants to invest the effort.

You can of course compile your own python.  But really, the best advice
is to move off of RHEL5.

 - J<

**Comment by nottellyou** [comment]
I use CentOS5.6 for many years, it's very stable and easy .

Which version of CentOS can support The last version of DenyHosts  ？？？？

**Comment by nottellyou** [comment]
My God!!

`[root@vagrant denyhosts-master]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from DenyHosts.util import normalize_whitespace
  File "/root/denyhosts-master/DenyHosts/util.py", line 9, in <module>
    import ipaddr
ImportError: No module named ipaddr
[root@vagrant denyhosts-master]# cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m`

Which version of CentOS can support The last version of DenyHosts ？？？？

**Comment by josev814** [comment]
You need to do pip install ipaddr.

**Comment by josev814** [comment]
If you look under the wiki I put an install guide for CentOS.  It's what I used to install denyhosts onto CentOS.

**Comment by nottellyou** [comment]
@josev814   OK, I will  look under the wiki, thank you.

**Comment by josev814** [comment]
The wiki is here.  https://github.com/denyhosts/denyhosts/wiki/
The install guide for centos is in the right menu under home.
Here's a direct link to it though.
https://github.com/denyhosts/denyhosts/wiki/Centos-Install-Guide

**Comment by josev814** [comment]
Something that I noticed today was if I do a ```pip install -U ipaddr``` it shows that pip was installed in python 2.7.  When trying to run ```python setup.py install``` I kept getting the message that ipaddr was missing.  When I did a ```python -V``` it shows me python 2.6.6.  So to install denyhosts I had to use ```/usr/bin/env python2.7 setup.py install``` to do the install.  Then in daemon-control I had to set python_bin from python to python2.7.  Then everything worked fine.

**Comment by jasontibbitts** [comment]
But note that doesn't remotely cover the question asked.  Those instructions simply won't work on Centos 5.

Generally I'd recommend to just install the EPEL package and be done with it, but the Centos 5 one is absolutely ancient.  I should probably just get it removed, though if anyone wants to point out the last version which can be used with that ancient python, I could try to get it in.

**Comment by josev814** [comment]
@jasontibbitts If you look at his updated post from 10 days ago he started using 6.8.  ```[root@vagrant denyhosts-master]# cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m```

**Comment by janpascal** [comment]
@nottellyou, since it seems you've moved to a more recent version of CentOS, is it OK if I close this issue?

**Comment by rctaptap** [comment]
Solution! https://www.bluenoob.com/linux/linux-bug/no-module-named-denyhosts-python_version.html
 cp -rp /usr/lib/python2.6/site-packages/DenyHosts /usr/lib/python2.7/site-packages/
