### ISSUE TITLE
Use of ipaddr module breaks python3 compatibility

### ISSUE THREAD

**Issue by jasontibbitts** [denyhosts/denyhosts#76]
So it seems that post-3.0 (in the 3.1 beta release, at least) a dependency on the ipaddr module was added.  But this module is unsupported upstream and is python2-specific.  No python3 port exists that I know of.  That's somewhat ironic as the 3.1 beta is supposed to improve python3 compatibility.

I guess the alternatives for me (as a distro maintainer) are:

* Patch out the use of that module
* Move back to legacy python
* Stay at 3.0.
* Port things to the ipaddress module, which is part of the standard library as of python 3.3 and has been backported as far as python 2.7.

Any idea on what would be preferred?

**Comment by slicer69** [comment]
I think removing the ipaddr makes the most sense. Most people are moving to Python 3+ and ipaddr is a relatively new feature in DenyHosts. I don't think many would complain if it was removed or made optional.

**Comment by jasontibbitts** [comment]
Actually I think a fix is just a couple of lines; I'll put one together when I get a few minutes.

**Comment by janpascal** [comment]
Python3 contains the ipaddress module, which has the same API as the ipaddr module used for python2.

**Comment by janpascal** [comment]
I think the following patch should fix this issue, could someone test with python3?

```
diff --git a/DenyHosts/util.py b/DenyHosts/util.py
index 6c9f5ba..b21a75b 100644
--- a/DenyHosts/util.py
+++ b/DenyHosts/util.py
@@ -6,7 +6,10 @@ from smtplib import SMTPHeloError
 import sys
 from textwrap import dedent
 import time
-import ipaddr
+try:
+    from ipaddress import IPAddress
+except ImportError:
+    from ipaddr import IPAddress

 from .constants import BSD_STYLE, TIME_SPEC_LOOKUP
 from .regex import TIME_SPEC_REGEX
@@ -169,7 +172,7 @@ def normalize_whitespace(string):

 def is_valid_ip_address(ip_address):
     try:
-        ip = ipaddr.IPAddress(ip_address)
+        ip = IPAddress(ip_address)
     except:
         return False
     if (ip.is_reserved or ip.is_private or ip.is_loopback or
```

**Comment by jasontibbitts** [comment]
I think that requirements.txt and setup.py also need changes to accommodate.

Frankly I think the best thing to do is to simply require IPAddress everywhere and not require python2 installs to use an unmaintained module.

**Comment by janpascal** [comment]
You're right about the `setup.py` and `requirements.txt`! I also didn't realized that `ipaddress` had been backported. I'll just have to look what happens when  `ipaddress` is a dependency but also (python > 3.4) part of the core.
