### ISSUE TITLE
Use new sync server address in default configuration

### ISSUE THREAD

**Issue by janpascal** [denyhosts/denyhosts#80]
Replace with sync.denyhosts.org:9911.

@slicer69, maybe you could have the deny.resonatingmedia.com address resolve/cname to the new sync server as well? This would make anyone with that address report to the new sync server automatically.

**Comment by slicer69** [comment]
Done, the domain should now forward to the new address.

**Comment by janpascal** [comment]
Thanks! 

Jesse Smith <notifications@github.com> schreef op 16 juli 2017 17:52:50 CEST:
>Done, the domain should now forward to the new address.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/denyhosts/denyhosts/issues/80#issuecomment-315618121

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
