### ISSUE TITLE
input breaks python 2 compatibility

### ISSUE THREAD

**Issue by Teszko** [denyhosts/denyhosts#84]
In python 2 the builtin input function is equivalent to eval(raw_input(prompt)) whereas in python 3 it's converted to a string [>>docs](https://docs.python.org/2/library/functions.html#input). This means the following [line](https://github.com/denyhosts/denyhosts/blob/0d5de1eb07ca53d519c382571fd96760cd2233ef/DenyHosts/denyfileutil.py#L69) is broken in python 2.

resulting in this error (tested with python 2.7 on debian stretch):
__________________________________
`python denyhosts.py --config denyhosts.conf --migrate

**** WARNING ****
migrate switch will migrate ALL your entries in your HOSTS_DENY file
and this can be potentially dangerous, if you have some entry that 
you won't purge

If you don't understand, please type 'No' and
read /usr/share/doc/denyhosts/README.Debian
for more info

Are you sure that you want do this? (Yes/No)Yes
Traceback (most recent call last):
  File "denyhosts.py", line 186, in <module>
    m = Migrate(prefs.get("HOSTS_DENY"))
  File "/home/user/git/denyhosts/DenyHosts/denyfileutil.py", line 69, in __init__
    response = input("Are you sure that you want do this? (Yes/No)")
  File "<string>", line 1, in <module>
NameError: name 'Yes' is not defined`
__________________________________

- There is also a hardcoded reference to [/usr/share/doc/denyhosts/README.Debian](https://github.com/denyhosts/denyhosts/blob/0d5de1eb07ca53d519c382571fd96760cd2233ef/DenyHosts/denyfileutil.py#L66), which should be removed.  
- The Migrate class has no coverage by unit tests.   

All these issues have been addressed in the PR I just created: #83

I took the freedom to add mock to requirements.txt for python < 3.3, as it makes writing sensible unit tests easier. I'm not sure how to inject user input without mock.  
mock comes with python >= 3.3 but requires a dependency for earlier versions.

**Comment by josev814** [comment]
PR #83 was merged, so I'm closing this issue
