### ISSUE TITLE
sync server

### ISSUE THREAD

**Issue by jammasterj89** [denyhosts/denyhosts#92]
I'm having issues using the sync server functionality, which server should I be using? I've tried the three I can find:

http://sync.denyhosts.org
http://deny.resonatingmedia.com
http://xmlrpc.denyhosts.net

But all of them give me the following error when it tries it sync:

> ERROR    [Errno 111] Connection refused
> Traceback (most recent call last):
>   File "/usr/share/denyhosts/DenyHosts/sync.py", line 136, in receive_new_hosts
>     self.__prefs.get("SYNC_DOWNLOAD_RESILIENCY"))
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
 >    return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
 >    verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
 >    return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
 >    self.send_content(h, request_body)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
>     connection.endheaders(request_body)
>   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 859, in send
>     self.connect()
>   File "/usr/lib/python2.7/httplib.py", line 836, in connect
>     self.timeout, self.source_address)
>   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
>     raise err
> error: [Errno 111] Connection refused

My denyhosts.conf settings are:

> SYNC_SERVER = http://xmlrpc.denyhosts.net:9911
> SYNC_INTERVAL = 1h
> SYNC_UPLOAD = no
> SYNC_DOWNLOAD = yes
> SYNC_DOWNLOAD_THRESHOLD = 10
> SYNC_DOWNLOAD_RESILIENCY = 5h

I've tried both installing the latest release manually from github, and from apt-get using Ubuntu, but both give me the above error. Thanks for the help!

**Comment by adriel** [comment]
Should be using:
`SYNC_SERVER = http://deny.resonatingmedia.com:9911`

As per whats in the default conf file https://github.com/denyhosts/denyhosts/blob/master/denyhosts.conf

**Comment by jammasterj89** [comment]
I've just set this up again and it now works and is happily ingesting new IPs. Not exactly sure what the issue was but it is working now, my apologies and thank you for the help.
